version: "3"

services:
  wsgi:
    image: wsgi
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    volumes:
      - ./docker/entrypoint.sh:/entrypoint.sh:ro
#      - ./docker/app:/app:ro
      - ./uwsgi_chunked/chunked.py:/app/uwsgi_chunked.py:ro
    ports:
      - 8000:8000
    environment:
      - STREAM=${STREAM}
