name: CI
on: [push, pull_request]
jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3'
          architecture: x64

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          python -m pip install -U pip~=21.0
          make deps
          pip install --timeout=30 -q -e .

      - name: Run tests
        run: make ci

      - name: Coveralls
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pipenv run coveralls --service=github